apiVersion: v1
kind: Secret
metadata:
  namespace: robot
  name: postgres-secret
type: Opaque
stringData:
  postgres-user: "postgres-user"
  postgres-password: "postgres-password"
  postgres-db: "postgres-db"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deploy
  namespace: robot
  labels:
    app: postgres-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-deploy
  template:
    metadata:
      labels:
        app: postgres-deploy
    spec:
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
      containers:
        - name: postgres
          image: postgres:13
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-db
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U agent_user -d robot_db
            initialDelaySeconds: 15
            periodSeconds: 5
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U agent_user -d robot_db
            initialDelaySeconds: 30
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: robot
  labels:
    app: postgres-deploy
spec:
  selector:
    app: postgres-deploy
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
