apiVersion: v1
kind: Pod
metadata:
  name: placeholder-name  # 동적으로 설정
  labels:
    agent-type: placeholder-agent-type  # 동적으로 설정
spec:
  containers:
    - name: placeholder-container-name  # 동적으로 설정
      securityContext:
        allowPrivilegeEscalation: true
        runAsUser: 0  # root 권한으로 실행
        runAsGroup: 0
        privileged: true  # 모든 권한 허용 (필요한 경우)
        capabilities:
          add:
          - SYS_ADMIN  # 시스템 관리 권한
          - DAC_OVERRIDE  # 파일 권한 우회
      image: pbc9236/pod_server:v0.0.5
      imagePullPolicy: IfNotPresent
      env:
        - name: MINIO_URL
          value: "minio-service.robot.svc.cluster.local:9000"
        - name: MINIO_ACCESS_KEY
          value: "minioadmin"
        - name: MINIO_SECRET_KEY
          value: "qwe1212qwe1212"
        - name: MINIO_BUCKET_NAME
          value: "rosbag-data"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: PYTHONIOENCODING  
          value: "UTF-8"

